### ISSUE TITLE
SSL Everywhere

### ISSUE THREAD

**Issue by ichbestimmtnicht** [supernova-ws/SuperNova#45] opened 2017-12-09 21:19 UTC
I like to test and contribute your game but login information without a secure Connection? No Way. 

Suggestion: The Certbot from the electronic frontier foundation is free and works with common browsers.
Website
https://certbot.eff.org/
or the direct link to the githubr epo
https://github.com/certbot/certbot

it suggest a forced 301 redirect to the encrypted url to avoid users using an unsecure connection. So dont let me open a next issue for that, please.

Greetings
ichbestimmtnicht

**Comment by supernova-ws** [comment] 2017-12-10 04:48
Why application should care about protocol level and enforce it?!

SN supports HTTPS connections so just setup your web server for desired behaviour.

**Comment by ichbestimmtnicht** [comment] 2017-12-10 22:31
chromium as well as firefox shows

This site can’t be reached

https://alpha.supernova.ws/login.php is unreachable.
ERR_ADDRESS_UNREACHABLE

**Comment by B1ll1am** [comment] 2017-12-14 04:31
Oh good lord, are you currently taking payments? Seriously, get a giant following  and make a million, then get back to the developer.

**Comment by ichbestimmtnicht** [comment] 2017-12-16 12:25
@supernova-ws Sending "...login information without a secure Connection? No Way." If this settings make your password easier discoverable for outsiders, its definitly this ONE setting that overhelm all other settings regardless how nice they are.
Furthermoore i made an english-language correction Commit.... The missing SSL does not stop me from trying to help.
@B1ll1am It is just offensive security. Not all users are aware of security and i just dont log in into websites without SSL. No fucking way!

**Comment by B1ll1am** [comment] 2017-12-17 20:00
Well then make your own server add a cert, they are free if you are not taking payments.
Issue resolved :)

**Comment by ichbestimmtnicht** [comment] 2017-12-17 20:44
This has nothing to do with payments! Most users are using a few (1!) passwords for various services. I think users with a minimum of security just wont use your website, are using '123' passwords or generating unique passwords as you should do. 
For me it just shows how 'gamer' and 'Nerd' differs. "The ape sits before the device" like we say in german. 
The point is that you scare exactly this possible users away that could help you with developement. Maybe just with exact Bug Reports but the better informed ones.... I dont want to take this disscussion anymore it was and is meant to help you.

**Comment by supernova-ws** [comment] 2017-12-17 21:05
There is absoultlу nothing insecure about payments.
Payments all are made via HTTPS and on the paysystems sites - no insecure info are held in SN or transferred via insecure channels.
Even if SN account was compromised (which requires MitM kind of attack) most which can make attacker - initiate payment which never be complete (by design) due of inability of attacker to pay - becuase there is no critical info about identity of player or his payment info stored on SN side.

**Comment by B1ll1am** [comment] 2017-12-18 01:56
Passwords, yeah if you are rocking the 123 passwords, it just giving that account away.  Try lastpass and tell all your friends too.  Here is the link just in case :) https://www.lastpass.com/

**Comment by ichbestimmtnicht** [comment] 2017-12-18 12:34
@B1ll1am That isn't the point. Most users just use one password and as a good developer you try to develop for the most stupid user that could use your program. For lazy gamers this means to keep them safe also in case of using one password emailadress and username for (bank)account (or other services that point to them paypal for example) and supernova.ws

As users we have to trust you to dont missuse our data anyway. For me the secure information delivery means that you activley keep track of userinformation security and so this is a "have to" feauture for all login services. The possiblity of payments have nothing to do with this @supernova-ws ! You want to store personal data so you have to keep track that you are the only one who can get it!

**Comment by supernova-ws** [comment] 2017-12-18 12:51
I really don't understand you. SN engine supports HTTPS in it's core. You can freely install SN on any SSL-supported server and it will work like a breeze! So what we are talking about here?

About my personal politics on my personal server? Why we talking about it on SN engine thread?

As you can see from sources (yes, you should not trust for a words) - SN does not gather and does not store any personal information from users (beyond email address which is not a personal info per-se). Password - by any means - is not a "personal informatiion" as defined in documents: it's not defines user and/or can't be used to identify user.

Anyway - google's "HTTPS EVERYWHERE" it's just a an evil hype. Do you know that google wants to rollout their own-issued SSL certificate services (or rolled out already)? Google simple wants to hold keys from each and every site - so it forces all site to switch to HTTPS. And guess - which service they would reccomend in Chrome and Android built-in browsers? Pretty clearly evil intensions.

**Comment by B1ll1am** [comment] 2017-12-18 17:43
Oh I forgot about those lazy gamers, you know we better force 2 factor authentication.
That's the only way we can make sure we are good to go.

**Comment by ichbestimmtnicht** [comment] 2017-12-19 16:10
yes it is exactly about this "About my personal politics on my personal server? Why we talking about it on SN engine thread?" please move it @supernova-ws 
@B1ll1am I dont use a mobilephone (Better:not the same SIM-card and i never carry one) for personal enjoyment (No calls when i am not at home) and security reasons (GPS-Tracking) for about 10 years. Very funny joke!

**Closed** 2017-12-19 23:05 UTC
